title: MultiPaper
description: Multi-server, single-world papermc implementation
theme: just-the-docs

url: https://multipaper.io/

aux_links:
  Download: https://multipaper.io/download.html
  GitHub: https://github.com/MultiPaper/MultiPaper
  Discord: https://discord.gg/dN3WCZkSRV

callouts:
  warning:
    title: Warning
    color: red

mermaid:
  version: "11.4.1"
