title: MultiPaper
description: Multi-server, single-world papermc implementation
theme: just-the-docs

url: https://multipaper.github.io/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
