title: MultiPaper
description: Multi-server, single-world papermc implementation
theme: just-the-docs

url: https://multipaper.github.io/

aux_links:
  GitHub: https://github.com/MultiPaper/MultiPaper
  Discord: https://discord.gg/dN3WCZkSRV

callouts:
  warning:
    title: Warning
    color: red
